import { useState, type RefObject } from 'react'

export interface FloatingText {
  id: string
  text: string
  color: string
  ref: RefObject<HTMLDivElement | null>
  //generated by function
  left?: number
  //generated by function
  top?: number
}

export function useFloatingTextEvents(){
  const [floatingTexts, setFloatingTexts] = useState<FloatingText[]>([])
  
  function addFloatingText(floatingText: FloatingText) {
    const run = async () => {
      const rect = floatingText.ref?.current?.getBoundingClientRect()
      if(!rect){
        console.error('No bounding client rect.', floatingText)
        return
      }
      setFloatingTexts(prev => [
        ...prev,
        {
          ...floatingText,
          left: rect.left - 15,
          top: rect.top
        }
      ])
    }
    run()
  }

  function removeFloatingText(id: string){
    if(!id) return
    setFloatingTexts(prev =>
      prev.filter(x => x.id !== id)
    )
  }

  return {
    floatingTexts,
    addFloatingText,
    removeFloatingText
  }
}