export type ContextMenuIconName =
  | 'settings'
  | 'player'
  | 'characters'
  | 'character_manage'
  | 'dashboard'
  | 'back'
  | 'close'
  | 'start'
  | 'stop'
  | 'recordLogs'
  | 'world'
  | 'notifications'
  | 'tutorial'
  | 'parties'
  | 'party_manage'
  | 'eye'
  | 'prohibited'