export type ContextMenuIconName =
  | 'settings'
  | 'player'
  | 'characters'
  | 'dashboard'
  | 'back'
  | 'close'
  | 'recordStart'
  | 'recordStop'
  | 'recordLogs'
  | 'world'
  | 'notifications'
  | 'tutorial'