export type OverlayMode = 'world'
  | 'character_quest'
  | 'character_hunt'
  | 'character_profession'
  | 'character_upgrade'

  | 'intro'
  | 'transition'
  | 'notifications'
  | 'dashboard'
  | 'tutorial'
  | 'adv_guild'
  | 'settings'
  | 'settings_debug_logs'

  | 'player'
  | 'player_create'

  | 'characters'
  | 'character_create'
  | 'character_manage'

  | 'party_list'
  | 'party'
  | 'party_manage'
  | 'party_create'
